foreach(REQUIRED_VAR WORKSPACE_DIR FS_CONTENT_DIR FS_PAYLOAD_DIR BOOT_BIN KERNEL_BIN FILESCANNER FSEDIT OUTPUT_IMG)
  if(NOT DEFINED ${REQUIRED_VAR})
    message(FATAL_ERROR "${REQUIRED_VAR} is required.")
  endif()
endforeach()

if(NOT IS_DIRECTORY "${FS_CONTENT_DIR}")
  message(FATAL_ERROR "FS content directory not found: ${FS_CONTENT_DIR}")
endif()

if(NOT IS_DIRECTORY "${FS_PAYLOAD_DIR}")
  message(FATAL_ERROR "FS payload directory not found: ${FS_PAYLOAD_DIR}")
endif()

set(WORKSPACE_BOOT "${WORKSPACE_DIR}/boot.bin")
set(WORKSPACE_KERNEL "${WORKSPACE_DIR}/kernel.bin")
set(WORKSPACE_IMG "${WORKSPACE_DIR}/c.img")
set(PROGRAMS_DIR "${WORKSPACE_DIR}/programs")
set(SCAN_OUTPUT "${WORKSPACE_DIR}/.filescanner-input.txt")

file(REMOVE_RECURSE "${WORKSPACE_DIR}")
file(MAKE_DIRECTORY "${WORKSPACE_DIR}")
file(COPY "${FS_CONTENT_DIR}/" DESTINATION "${WORKSPACE_DIR}")
file(COPY "${FS_PAYLOAD_DIR}/" DESTINATION "${WORKSPACE_DIR}")
file(COPY_FILE "${BOOT_BIN}" "${WORKSPACE_BOOT}" ONLY_IF_DIFFERENT)
file(COPY_FILE "${KERNEL_BIN}" "${WORKSPACE_KERNEL}" ONLY_IF_DIFFERENT)

# Keep .gitkeep in source tree for version control, but never pack it into c.img.
file(GLOB_RECURSE GITKEEP_FILES "${WORKSPACE_DIR}/.gitkeep")
if(GITKEEP_FILES)
  file(REMOVE ${GITKEEP_FILES})
endif()

file(GLOB_RECURSE LEGACY_EXE_FILES "${PROGRAMS_DIR}/*.exe")
if(LEGACY_EXE_FILES)
  file(REMOVE ${LEGACY_EXE_FILES})
endif()

execute_process(
  COMMAND "${FILESCANNER}"
  WORKING_DIRECTORY "${WORKSPACE_DIR}"
  RESULT_VARIABLE FILESCANNER_RESULT
  ERROR_VARIABLE FILESCANNER_ERROR
  OUTPUT_FILE "${SCAN_OUTPUT}"
)

if(NOT FILESCANNER_RESULT EQUAL 0)
  message(FATAL_ERROR "filescanner failed (${FILESCANNER_RESULT}): ${FILESCANNER_ERROR}")
endif()

execute_process(
  COMMAND "${FSEDIT}" c.img c
  WORKING_DIRECTORY "${WORKSPACE_DIR}"
  INPUT_FILE "${SCAN_OUTPUT}"
  RESULT_VARIABLE FSEDIT_RESULT
  ERROR_VARIABLE FSEDIT_ERROR
)

file(REMOVE "${SCAN_OUTPUT}")

if(NOT FSEDIT_RESULT EQUAL 0)
  message(FATAL_ERROR "fsedit failed (${FSEDIT_RESULT}): ${FSEDIT_ERROR}")
endif()

get_filename_component(OUTPUT_DIR "${OUTPUT_IMG}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
file(COPY_FILE "${WORKSPACE_IMG}" "${OUTPUT_IMG}" ONLY_IF_DIFFERENT)